// Auth
export const AUTH_WATCH_START = 'AUTH_WATCH_START'
export const AUTH_CHANGED = 'AUTH_CHANGED'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
export const AUTH_LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED'

// User
export const USER_WATCH_START = 'USER_WATCH_START'
export const USER_WATCH_ERROR = 'USER_WATCH_ERROR'
export const USER_WATCH_STOP = 'USER_WATCH_STOP'
export const USER_CHANGED = 'USER_CHANGED'
export const USER_SAVE = 'USER_SAVE'
export const USER_SAVE_SUCCESS = 'USER_SAVE_SUCCESS'
export const USER_SAVE_FAILED = 'USER_SAVE_FAILED'
